### PR TITLE
Minor updates to SVGs

### PR DESCRIPTION
**Pull request by boomskats**
just some minor sunday evening inkscaping

### CODE REVIEW

**Comment by hoytech** [comment]
Thank you! I like the rounded outside corners on the Q. Is the "tail" on the Q getting clipped off in your browser? It looks cut off to me (chromium/linux).

**Comment by boemska-nik** [comment]
Fixed! 

You wanna leave this PR open and I'll make a couple of other updates?

**Comment by hoytech** [comment]
Looks great thanks! Sure, I'll leave this PR open if you're planning on making more improvements. Let me know when it's ready to merge. Appreciate it!

**Comment by hoytech** [comment]
I'm going to merge this now, since I am going to make a few changes and want to avoid merge conflicts. Please open up a new PR if needed. Thanks!

**Pull request merged**
